# action.yml
name: "Auto Tag Version"
description: ""
inputs:
  poetry-version:
    description: ""
    default: "1.6.1"
  version-prefix:
    description: ""
    default: "v"
  github-token:
    description: ""
    required: true
# runs:
#   using: "composite"
#   steps:
#     - run: |
#         pip install poetry==${{ inputs.poetry-version }}
#         pip install PyGithub
#       shell: bash
#     - run: python main.py
#       shell: bash
runs:
  using: docker
  image: Dockerfile
