# action.yml
name: "Auto Tag Version"
description: ""
inputs:
  poetry-version:
    description: ""
    default: "1.6.1"
  version-prefix:
    description: ""
    default: "v"
  github-token:
    description: ""
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.poetry-version }}
    - ${{ inputs.version-prefix }}
    - ${{ inputs.github-token }}
