# action.yml
name: "Auto Tag Version"
description: ""
inputs:
  poetry-version:
    description: ""
    default: "1.6.1"
  version-prefix:
    description: ""
    default: "v"
  github-token:
    description: ""
    required: true
  github-repository:
    description: ""
    required: true
runs:
  using: "composite"
  steps:
    - run: pip install poetry==${{ inputs.poetry-version }}
      shell: bash
    - run: |
        TAG=v$(poetry version -s)
        if [ $(git tag -l "${TAG}") ]
        then
          echo "Tag ${TAG} already exists"
        else
          git tag ${TAG} && git push origin ${TAG}
        fi
      shell: bash
