# action.yml
name: "Auto Tag Version"
description: ""
inputs:
  version-prefix:
    description: ""
    default: "v"
  github-token:
    description: ""
    required: true
  github-repository:
    description: ""
    required: true
runs:
  using: docker
  image: narumi/auto-tag-version:latest
  args:
    - ${{ inputs.version-prefix }}
    - ${{ inputs.github-token }}
    - ${{ inputs.github-repository }}
